const novedades = [
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
    {
        id: 1,
        titulo: "The Witcher 3: Wild Hunt's Next-Gen Update Arrives This December",
        descripcion: "Return to The Continent.",
        texto: "CD Projekt Red has announced that the PlayStation 5, Xbox Series, and PC next-gen update for The Witcher 3: Wild Hunt will be released on December 14. Announced in a post on The Witcher's official Twitter account (below), CD Projekt Red has stuck to its promise of a fourth quarter release by confirming the December date. This only applies to the digital version of the game though, with CD Projekt Red saying that a physical release date will be announced later. The upgrade, which is free to anyone who's bought the game previously, includes dozens of visual, performance, and technical enhancements over the original, CD Projekt Red said in a press release. These include ray tracing support, faster loading times on consoles, as well as a variety of mods integrated into the experience, among many others. The next-gen update for The Witcher 3: Wild Hunt is coming on December 14th, free for everyone who already owns the game. For more details and gameplay reveal, tune in to REDstreams next week on https://t.co/IpFERTohi9. pic.twitter.com/fg3yfGeNih — The Witcher (@witchergame) November 14, 2022. More details on these integrated mods and other features will be shared during a Twitch livestream sometime next week, but CD Projekt Red has otherwise confirmed the next-gen version to include all previously released DLC alongside new content based on The Witcher Netflix series. The game was originally expected to be released last year before being delayed twice, with third party studio Saber Interactive originally developing the new version. CD Projekt Red took over itself in April 2022, though persisted that the game was not in development hell. The Q4 date was set back in May but many were still worried given the two previous delays, not to mention the impending end of the year, but CD Projekt Red will seemingly meet its target. In our 9/10 review of the original release, IGN said: Massive in size, and meticulously detailed, The Witcher 3 ends Geralt's story on a high note, and it also won our Game of the Year.",
        image: "../image/novedades1.jpg"
    },
];


let divNovedades = document.createElement('div');
divNovedades.id = 'novedades';

const cardNovedades = (novedades) => {
    divNovedades.innerHTML = '';
    divNovedades.className = 'container mt-5 py-5';

    let divCard1 = document.createElement('div');
    divCard1.className = 'row row-cols-1 row-cols-md-3 g-4';

    divResultado.append(divCard1); 

    let main = document.getElementById('main');
    main.append(divResultado);
}